apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: spring-demo-app
  name: spring-demo-app
spec:
  ports:
  - name: 8080-8080
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: spring-demo-app
  type: LoadBalancer

