apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: spring-actuator
  name: spring-actuator
  namespace: spring-actuator
spec:
  ports:
    - name: 8080-8080
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: spring-actuator
  type: LoadBalancer
