apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: spring-actuator
  name: spring-actuator
  namespace: pve-spring
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-actuator
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spring-actuator
    spec:
      containers:
      - image: draco.tanzu.lab/spring/demo
        ports:
        - containerPort: 8080
        name: demo
        env:
          - name: JAVA_OPTS
            value: >-
              -DTELEGRAF_URL=http://aria-telegraf-collector.aria-k8s.svc.cluster.local:2878

        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          seccompProfile:
            type: "RuntimeDefault"
          capabilities:
            drop: ["ALL"]
status: {}
